app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from . import db, login_manager


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))
    orders = db.relationship('Order', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username


class Store(db.Model):
    __tablename__ = 'stores'
    id = db.Column(db.Integer, primary_key=True)
    storename = db.Column(db.String(64), unique=True, index=True)
    dishes = db.relationship('Dish', backref='store', lazy='dynamic')
    orders = db.relationship('Order', backref='store', lazy='dynamic')

    def __init__(self, storename):
        self.storename = storename

    @property
    def serialize(self):
        return {
            'id'        :self.id,
            'storename' :self.storename
        }
    
    def __repr_(self):
        return '<Store %r>' % self.storename

    

    
class Dish(db.Model):
    __tablename__ = 'dishes'
    id = db.Column(db.Integer, primary_key=True)
    dishname =  db.Column(db.String(64), unique=True, index=True)
    dishprice = db.Column(db.Numeric)
    store_id = db.Column(db.Integer, db.ForeignKey('stores.id'))
    orders = db.relationship('Order', backref='dish', lazy='dynamic')
    
    @property
    def serialize(self):
        return {
            'id'        :self.id,
            'dishname'  :self.dishname,
            'price'     :round(self.dishprice,2),
            'store_id'  :self.store_id
    }

    def __repr__(self):
        return '<Dish %r>' % self.dishname

    
class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    store_id = db.Column(db.Integer, db.ForeignKey('stores.id'))
    dish_id = db.Column(db.Integer, db.ForeignKey('dishes.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    quantity = db.Column(db.Integer)
    date = db.Column(db.DateTime)
    state = db.Column(db.Integer)
    @property
    def serialize(self):
        return {
            'id'        :self.id,
            'store_id'  :self.store_id,
            'user_id'   :self.user_id,
            'quantity'  :self.quantity,
            'date'      :self.date,
            'state'     :self.state
    }
    def __repr__(self):
        return '<Order %r>' % self.id

class ShopOwner(db.Model):
    __tablename__ = 'shopowners'
    id = db.Column(db.Integer, primary_key=True)
    store_id = db.Column(db.Integer, db.ForeignKey('stores.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, DateTimeField, HiddenField
from wtforms.validators import Required


class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')


class TimePickerForm(Form):
    storeid = StringField('Store', validators=[Required()])
    dishid = StringField('Dish', validators=[Required()])
    time = DateTimeField('Time', format='%m/%d/%Y %H:%M', validators=[Required])
    submit = SubmitField('Submit')

class StateUpdateForm(Form):
	state = HiddenField('State')
	submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api')

    from .manage import manage as manage_blueprint
    app.register_blueprint(manage_blueprint, url_prefix='/manage')

    return app

app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import stores, dishes, orders

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, jsonify, flash, url_for, redirect, request
from flask import json as json2
from . import main
from .. import db
from ..models import Store
from ..models import Dish
from ..models import Order, User
from .forms import TimePickerForm, StateUpdateForm
from flask.ext.login import current_user, login_required
from datetime import datetime

@main.route('/')
@login_required
def index():
    timeform = TimePickerForm()
    stores = Store.query.all()
    stores_json = jsonify({'stores':[i.serialize for i in stores]})
    dishes = Dish.query.all()
    return render_template('index.html', stores=stores, stores_json=stores_json, dishes=dishes, timeform=timeform)

@main.route('/manage')
@login_required
def manage():
    form = StateUpdateForm()
    if current_user.role_id == 2:
        orders = db.session.query(Order).join(Store, Store.id == Order.store_id).join(Dish, Dish.id == Order.dish_id).join(User, User.id == Order.user_id).order_by(Order.date.asc())
        #orders = Order.query.all()
        return render_template('manage/manage.html', orders = orders, form=form, current_time=datetime.utcnow())
    else:
        return "Unauthorized User."

@main.route('/submit-order', methods=['GET','POST'])
def submit_order():
    form = TimePickerForm()
    if (form.validate_on_submit()):
        new_order = Order(store_id = form.storeid.data, dish_id =form.dishid.data, user_id = current_user.id, date = form.time.data, state=True)
		#state = True # 1: unprocessed 2: processed 0: missed 
        db.session.add(new_order)
        db.session.commit()
        flash('New order has been added!')
        return redirect(url_for('main.index'))
    timeform = TimePickerForm()
    stores = Store.query.all()
    stores_json = jsonify({'stores':[i.serialize for i in stores]})
    dishes = Dish.query.all()
    return render_template('index.html', stores=stores, stores_json=stores_json, dishes=dishes, timeform=timeform)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Cafeteria - Berkley{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Cafeteria - Berkley</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Shop</a></li>
                {% if current_user.role_id == 2 %}
                <li><a href="{{ url_for('main.manage') }}">Orders</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}Cafeteria - Berkley{% endblock %}
{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename = 'style.css') }}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css"></script>
{% endblock %}
{% block page_content %}
<div class="page-header">
  <h1>Hello, {% if current_user.is_authenticated() %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
{% for store in stores %}
      <h1>{{ store.storename }}</h1>
      {% for dish in dishes %}
          {% if dish.store_id == store.id %}
          <div class="col-md-2 column productbox">
              <img src="http://placehold.it/460x250/e67e22/ffffff&text={{ dish.dishname }}" class="img-responsive">  
                  <div class="producttitle">{{ dish.dishname }}</div>
                    <div class="productprice">
		      <div class="pull-right">
			<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#dishModal" data-storeid="{{ store.id }}" data-dishid="{{ dish.id }}">pick!</button>
		      </div>
		    <div class="pricetext">${{'%0.1f'| format(dish.dishprice|float)}}</div>
          </div>
	  </div>	     
	  {% endif %}
      {% endfor %}
      <div class="clearfix"></div>
{% endfor %}

<div class="modal fade" id="dishModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
	<div class="modal-dialog" role="document">
	
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	      <h4 class="js-title-step"></h4>
	    </div>
	    <div class="modal-body">
	    	<form method="POST" role="form" id="orderform">
	    	<div class="row hide" data-step="1" data-title="When do you want to pick up?">
		    	<div class="form-group">
	     			<label for="text">{{ timeform.storeid.label }}:</label>
					{{ timeform.storeid(class='storeid form-control', readonly=true, type="hidden") }}
					<input class="storename form-control" readonly>
	  			</div>	
		        <div class="form-group">
	     			<label for="text">{{ timeform.dishid.label }}:</label>
					{{ timeform.dishid(class='dishid form-control', readonly=true, type="hidden") }}
					<input class="dishname form-control" readonly>
	  			</div>	
		        <div class="form-group">
	     			<label for="text"> {{ timeform.time.label }}: </label>
					{{ timeform.time(id='datetimepicker1',class='form-control') }}
	  			</div>
  			</div>
  		    </form>
  		    <form method="POST" role="form" method="POST" id="orderconfirm" action="submit-order">
  			<div class="row hide" data-step="2" data-title="Please confirm your order">
  				{{ timeform.hidden_tag() }}
          		<div class="form-group">
	     			<label for="text">{{ timeform.storeid.label }}:</label>
					{{ timeform.storeid(class='storeid form-control', readonly=true, type="hidden") }}
					<input class="storename form-control" readonly>
	  			</div>	
		       
		        <div class="form-group">
	     			<label for="text">{{ timeform.dishid.label }}:</label>
					{{ timeform.dishid(class='dishid form-control', readonly=true, type="hidden") }}
					<input class="dishname form-control" readonly>
	  			</div>	
		        <div class="form-group">
	     			<label for="text"> {{ timeform.time.label }}: </label>
					{{ timeform.time(id='datetimepicked',class='form-control', readonly=true) }}
	  			</div>
        	</div>
            </form>
        </div>
	    <div class="modal-footer">
	        <button type="button" class="btn btn-default js-btn-step pull-left" data-orientation="cancel" data-dismiss="modal">Cancel</button>
	        <button type="button" class="btn btn-warning js-btn-step" data-orientation="previous">Previous</button>
	        <button type="button" class="btn btn-success js-btn-step" data-orientation="next">Next</button>
		</div>
		</div>
	  </div>
	</div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript">
  
  $('#dishModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var dishid = button.data('dishid') // Extract info from data-* attributes
  var storeid = button.data('storeid') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
 
  $.ajax({
  	url:"/api/stores/"+storeid,
  	dataType: "json"
  }).done(function (data){
  	store = data;
  	modal.find('.modal-body .storename').val(store.storename)
  	modal.find('.modal-body .storeid').val(storeid)
  })
  
  $.ajax({
  	url:"/api/dishes/"+dishid,
  	dataType: "json"
  }).done(function (data){
  	dish = data;
  	modal.find('.modal-body .dishname').val(dish.dishname)
  	modal.find('.modal-body .dishid').val(dishid)
  })
  })
</script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery-bootstrap-modal-steps.js') }}"></script>
<script type="text/javascript">
  var callback1 = function(){
  	$("#datetimepicked").val($("#datetimepicker1").val());
  	$("#datetimepicked").attr('value', $("#datetimepicker1").val());
  	$("#orderform").submit(function(e) {
  		e.preventDefault();
  	});
  }
  $('#dishModal').modalSteps({
	btnCancelHtml: 'Cancel',
	btnPreviousHtml: 'Previous',
	btnNextHtml: 'Next',
	btnLastStepHtml: "Submit",
	disableNextButton: false,
	completeCallback: function(){
		$("#orderconfirm").submit()
	},
	callbacks: {
		'2': callback1
	}
	});
</script>
<script type="text/javascript" src="{{ url_for('static', filename='moment.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='bootstrap-datetimepicker.min.js') }}"></script>
<script type="text/javascript">
	$('#datetimepicker1').datetimepicker({
		format: 'MM/DD/YYYY HH:mm',
		minDate: moment().add(2, 'hour'),
		maxDate: moment().add(2, 'd')
	})
</script>
{% endblock %}